fix(client): null check for JWKS validation
Prevents exception if "jwks" client configuration is set to null:
```
TypeError: Cannot read properties of null (reading 'keys')\n    at validateJWKS
(node_modules/.pnpm/oidc-provider@8.4.1/node_modules/oidc-provider/lib/models/client.js:41:29
```